parameters:
    bigfoot_content.template.class: 'Bigfoot\Bundle\ContentBundle\Services\Template'
    bigfoot_content.widgettype.class: 'Bigfoot\Bundle\ContentBundle\Form\WidgetType'
    bigfoot_content.widgettesttype.class: 'Bigfoot\Bundle\ContentBundle\Form\WidgetTestType'
    bigfoot_content.sidebartype.class: 'Bigfoot\Bundle\ContentBundle\Form\SidebarType'
    bigfoot_content.staticcontenttype.class: 'Bigfoot\Bundle\ContentBundle\Form\StaticContentType'
    bigfoot_content.pagetype.class: 'Bigfoot\Bundle\ContentBundle\Form\PageType'
    bigfoot_content.display_content.class: 'Bigfoot\Bundle\ContentBundle\Services\DisplayContent'

services:
    bigfoot_content.template:
            class: '%bigfoot_content.template.class%'
    bigfoot_bundle_contentbundle_widgettype:
            class: '%bigfoot_content.widgettype.class%'
            tags:
                - { name: form.type, alias: bigfoot_bundle_contentbundle_widgettype}
    bigfoot_bundle_contentbundle_widgettesttype:
            class: '%bigfoot_content.widgettesttype.class%'
            tags:
                - { name: form.type, alias: bigfoot_bundle_contentbundle_widgettesttype}
    bigfoot_bundle_contentbundle_sidebartype:
            class: '%bigfoot_content.sidebartype.class%'
            tags:
                - { name: form.type, alias: bigfoot_bundle_contentbundle_sidebartype}
    bigfoot_bundle_contentbundle_pagetype:
            class: '%bigfoot_content.pagetype.class%'
            tags:
                - { name: form.type, alias: bigfoot_bundle_contentbundle_pagetype}
    bigfoot_bundle_contentbundle_staticcontenttype:
            class: '%bigfoot_content.staticcontenttype.class%'
            tags:
                - { name: form.type, alias: bigfoot_bundle_contentbundle_staticcontenttype}
    bigfoot_content.display_content:
            class: '%bigfoot_content.display_content.class%'
            arguments: [@service_container]
    kernel.listener.bigfoot_content_menu_listener:
        class: Bigfoot\Bundle\ContentBundle\Listener\MenuListener
        tags:
            - { name: kernel.event_listener, event: bigfoot.menu.generate, method: onMenuGenerate }
    bigfoot_content.twig.content_renderer_extension:
        class: Bigfoot\Bundle\ContentBundle\Twig\ContentRendererExtension
        arguments: [@bigfoot_content.display_content]
        tags:
            - { name: twig.extension }
